#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/buildbeat-skill-only.XXXXXX")"
PROJECT="$TMP_ROOT/project"
FAKE_BIN="$TMP_ROOT/no-node-bin"

cleanup() {
  rm -rf -- "$TMP_ROOT"
}
trap cleanup EXIT

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  exit 1
}

mkdir -p "$PROJECT" "$FAKE_BIN"
cp -R "$REPO_ROOT/templates/." "$PROJECT/"
# Optional project-owned standards and ADR libraries are available upstream but
# are not generated by default on the Skill/manual path.
rm -rf -- "$PROJECT/standards" "$PROJECT/pm/adr"

# Model the Skill/manual bootstrap path: copy the canonical templates, then fill
# only deterministic project choices. No CLI manifest or Node runtime is needed.
mv "$PROJECT/pm/当期看板.md" "$PROJECT/pm/测试期-看板.md"
cp "$REPO_ROOT/tests/fixtures/healthy-default/project/pm/NOW.md" "$PROJECT/pm/NOW.md"
cp "$REPO_ROOT/tests/fixtures/healthy-default/project/pm/测试期-看板.md" "$PROJECT/pm/测试期-看板.md"
cp "$REPO_ROOT/tests/fixtures/healthy-default/project/pm/decisions.md" "$PROJECT/pm/decisions.md"
cp "$REPO_ROOT/tests/fixtures/healthy-default/project/pm/status/README.md" "$PROJECT/pm/status/README.md"
cp "$REPO_ROOT/tests/fixtures/healthy-default/project/pm/changes/README.md" "$PROJECT/pm/changes/README.md"
cp "$REPO_ROOT/tests/fixtures/healthy-default/project/contracts/PROTOCOL.md" "$PROJECT/contracts/PROTOCOL.md"
cp "$REPO_ROOT/tests/fixtures/healthy-default/project/.gitignore" "$PROJECT/.gitignore"
rm -f -- "$PROJECT/gitignore.template"
chmod +x "$PROJECT"/scripts/*.sh

cat > "$FAKE_BIN/node" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' 'node must not be called by the Skill-only path' >&2
exit 99
EOF
chmod +x "$FAKE_BIN/node"

git -C "$PROJECT" init -q
git -C "$PROJECT" config user.name "BuildBeat Tests"
git -C "$PROJECT" config user.email "tests@example.invalid"
git -C "$PROJECT" add .
git -C "$PROJECT" commit -qm "Skill-only fixture baseline"

set +e
OUTPUT=$(cd "$PROJECT" && PATH="$FAKE_BIN:$PATH" BUS_CHECK_NO_FETCH=1 BUS_CHECK_NO_LIVE=1 bash scripts/bus-check.sh --strict 2>&1)
STATUS=$?
set -e

[ "$STATUS" -eq 0 ] || {
  printf '%s\n' "$OUTPUT" >&2
  fail "Skill-only scaffold failed strict bus-check (exit $STATUS)"
}
printf '%s\n' "$OUTPUT" | grep -F 'NOW 薄、看板归位、status 克制' >/dev/null \
  || fail "Skill-only scaffold did not report a healthy coordination layer"
[ ! -e "$PROJECT/.buildbeat/manifest.json" ] && [ ! -e "$PROJECT/.solobaton/manifest.json" ] \
  || fail "Skill-only bootstrap unexpectedly created a CLI manifest"
[ ! -e "$PROJECT/standards" ] && [ ! -e "$PROJECT/pm/adr" ] \
  || fail "Skill-only bootstrap unexpectedly generated optional standards or ADR files"

printf '%s\n' 'PASS: Skill-only scaffold works without invoking Node or creating a CLI manifest'
